<?php
/**
 * @author Sachindra Awasthi
 * @copyright Copyright (c) 2022 Fahim (https://www.Fahimwebtechnology.com/)
 * @package Fahim_SiteMap
 */
?>
<?php
/**
 * SEO Toolbar template
 *
 * @var $block Fahim\SiteMap\Block\ProductCollection
 */
?>
<?php
$helper = $block->getHelper();

//Product Link
$enableProduct = $helper->isEnableProduct();
$titleProduct = $helper->titleProduct();

if ($enableProduct) : ?>
    <h2 class="Fahim_h2"><?php echo $titleProduct; ?></h2>
    <div class="Fahim_site_map_grid">
        <?php
        $productCollection = $block->getProductCollection();
        foreach ($productCollection as $product) {
            echo $product->getData("id");
            echo '<div class="col-Fahim-3">
                    <h3 class="Fahim_product_list">
                    <a href="'.$product->getUrlModel()->getUrl($product).'"
                    title = "'.$product->getName().'">'.$product->getName().'</a>
                    </h3>
                </div>';
        }
        ?>
    </div>
    <?php
endif; ?>